sudo: required

language: python

dist: xenial

python:
  - "3.6"

install:
  - pip install flake8

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master
    - develop

before_install:
  # Update docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Build docker image
  - if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "$TRAVIS_TAG";
      docker build -t "$DOCKER_USERNAME"/wordofthedaytelegrambot:"$TRAVIS_TAG" . ;
      docker run -d --name=wordofthedaytelegrambot
      --mount type=bind,source=$TRAVIS_BUILD_DIR/data/,target=/opt/wordofthedaytelegrambot/data/
      --mount type=bind,source=$TRAVIS_BUILD_DIR/conf/.token,target=/opt/wordofthedaytelegrambot/conf/.token
      --mount type=bind,source=$TRAVIS_BUILD_DIR/logs/,target=/opt/wordofthedaytelegrambot/logs/
      "$DOCKER_USERNAME"/wordofthedaytelegrambot:"$TRAVIS_TAG" ;
    else
      docker build -t "$DOCKER_USERNAME"/wordofthedaytelegrambot . ;
      docker run -d --name=wordofthedaytelegrambot
      --mount type=bind,source=$TRAVIS_BUILD_DIR/data/,target=/opt/wordofthedaytelegrambot/data/
      --mount type=bind,source=$TRAVIS_BUILD_DIR/conf/.token,target=/opt/wordofthedaytelegrambot/conf/.token
      --mount type=bind,source=$TRAVIS_BUILD_DIR/logs/,target=/opt/wordofthedaytelegrambot/logs/
      "$DOCKER_USERNAME"/wordofthedaytelegrambot ;
    fi;
  - echo "$TELEGRAM_TOKEN" > conf/.token
  # run docker container
  - docker run -d --name=wordofthedaytelegrambot
    --mount type=bind,source=$TRAVIS_BUILD_DIR/data/,target=/opt/wordofthedaytelegrambot/data/
    --mount type=bind,source=$TRAVIS_BUILD_DIR/conf/.token,target=/opt/wordofthedaytelegrambot/conf/.token
    --mount type=bind,source=$TRAVIS_BUILD_DIR/logs/,target=/opt/wordofthedaytelegrambot/logs/
    "$DOCKER_USERNAME"/wordofthedaytelegrambot
  - docker ps -a
  - docker stats --no-stream

after_success:
  # Update online image
  - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin;
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker push "$DOCKER_USERNAME"/wordofthedaytelegrambot:"$TRAVIS_TAG";
      fi;
    elif [ "$TRAVIS_BRANCH" == "develop" ]; then
      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker push "$DOCKER_USERNAME"/wordofthedaytelegrambot;
      fi;
    fi;

script:
  - flake8 . --max-line-length=120